### ISSUE TITLE
Error when running 'npm install'

### ISSUE THREAD

**Issue by shlomsky** [sbstjn/node-blog#1]
```
npm http GET https://registry.npmjs.org/kickstart
npm http GET https://registry.npmjs.org/node-markdownblog
npm http 304 https://registry.npmjs.org/node-markdownblog

npm ERR! Error: No compatible version found: node-markdownblog@'>=1.0.1'
npm ERR! No valid targets found.
npm ERR! Perhaps not compatible with your version of node?
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:488:10)
npm ERR!     at next_ (/usr/local/lib/node_modules/npm/lib/cache.js:438:17)
npm ERR!     at next (/usr/local/lib/node_modules/npm/lib/cache.js:415:44)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:408:5
npm ERR!     at saved (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:231:7)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 10.8.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/brianandrich/Sites/node-blog
npm ERR! node -v v0.6.11
npm ERR! npm -v 1.1.1
npm ERR! message No compatible version found: node-markdownblog@'>=1.0.1'
npm ERR! message No valid targets found.
npm ERR! message Perhaps not compatible with your version of node?
npm http 304 https://registry.npmjs.org/kickstart
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/brianandrich/Sites/myblog/npm-debug.log
npm not ok
```

**Comment by sbstjn** [comment]
I'm so sorry, this is entirely my fault. I'll push an update later to fix that issue…

**Comment by shlomsky** [comment]
Thanks, man! Awesome app, btw. I'm hoping to reverse engineer it to better my understanding of nodejs

**Comment by sbstjn** [comment]
Please pull the latest changes from the repository or download it again and you should be able to install the needed dependencies. 

node-blog may not have the best code for getting started with node.js, you should definitely take a look at [node-kickstart](https://github.com/semu/node-kickstart-example). It's a simple wrapper for the awesome [express.js](http://expressjs.com/) framework and a good start point for creating node.js web apps with jade template rendering and lesscss parsing:

https://github.com/semu/node-kickstart
https://github.com/semu/node-kickstart-example
